######################################################################
# Automatically generated by qmake (3.0) Do. Juni 23 15:18:59 2016
######################################################################

TEMPLATE = app
TARGET = QT_dev
INCLUDEPATH += .

# Input
HEADERS += Taschenrechner.h ui_Taschenrechner.h
SOURCES += main.cpp qt_test.cpp Taschenrechner.cpp
